/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ProcexpHelperInterface -p ProcexpHelperInterface procexphelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef PROCEXPHELPERINTERFACE_H
#define PROCEXPHELPERINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.procexp.helper
 */
class ProcexpHelperInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.procexp.helper"; }

public:
    ProcexpHelperInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ProcexpHelperInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void exec(int process_pid, int process_tgid);
    void exit(int process_pid, int process_tgid, int exit_code);
    void fork(int parent_pid, int parent_tgid, int child_pid, int child_tgid);
    void gid(int process_pid, int process_tgid, int rgid, int egid);
    void uid(int process_pid, int process_tgid, int ruid, int euid);
};

namespace com {
  namespace procexp {
    typedef ::ProcexpHelperInterface helper;
  }
}
#endif
