/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ProcexpHelperAdaptor -c ProcexpHelperAdaptor procexphelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PROCEXPHELPERADAPTOR_H
#define PROCEXPHELPERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.procexp.helper
 */
class ProcexpHelperAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.procexp.helper")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.procexp.helper\">\n"
"    <signal name=\"fork\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"parent_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"parent_tgid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"child_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"child_tgid\"/>\n"
"    </signal>\n"
"    <signal name=\"exec\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_tgid\"/>\n"
"    </signal>\n"
"    <signal name=\"uid\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_tgid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"ruid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"euid\"/>\n"
"    </signal>\n"
"    <signal name=\"gid\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_tgid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"rgid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"egid\"/>\n"
"    </signal>\n"
"    <signal name=\"exit\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_pid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"process_tgid\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"exit_code\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ProcexpHelperAdaptor(QObject *parent);
    virtual ~ProcexpHelperAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void exec(int process_pid, int process_tgid);
    void exit(int process_pid, int process_tgid, int exit_code);
    void fork(int parent_pid, int parent_tgid, int child_pid, int child_tgid);
    void gid(int process_pid, int process_tgid, int rgid, int egid);
    void uid(int process_pid, int process_tgid, int ruid, int euid);
};

#endif
